//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceEvidence.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tesseract-master.1153")]
        public string TesseractDirectory {
            get {
                return ((string)(this["TesseractDirectory"]));
            }
            set {
                this["TesseractDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ces+eng")]
        public string TesseractLanguages {
            get {
                return ((string)(this["TesseractLanguages"]));
            }
            set {
                this["TesseractLanguages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int MainFormVerticalScrollbarPlaceholderWith {
            get {
                return ((int)(this["MainFormVerticalScrollbarPlaceholderWith"]));
            }
            set {
                this["MainFormVerticalScrollbarPlaceholderWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color InvoiceNewBackColor {
            get {
                return ((global::System.Drawing.Color)(this["InvoiceNewBackColor"]));
            }
            set {
                this["InvoiceNewBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 100, 100")]
        public global::System.Drawing.Color InvoiceOldBackColor {
            get {
                return ((global::System.Drawing.Color)(this["InvoiceOldBackColor"]));
            }
            set {
                this["InvoiceOldBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("730")]
        public int InvoiceOldDaysCount {
            get {
                return ((int)(this["InvoiceOldDaysCount"]));
            }
            set {
                this["InvoiceOldDaysCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int InvoiceNewDaysCount {
            get {
                return ((int)(this["InvoiceNewDaysCount"]));
            }
            set {
                this["InvoiceNewDaysCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string TesseractTemporalDirectory {
            get {
                return ((string)(this["TesseractTemporalDirectory"]));
            }
            set {
                this["TesseractTemporalDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainFormExtendedView {
            get {
                return ((bool)(this["MainFormExtendedView"]));
            }
            set {
                this["MainFormExtendedView"] = value;
            }
        }
    }
}
